{% set name = "pynvml" %}
{% set version = '8.0.2' %}

package:
  name: {{ name|lower }}
  version: {{version}}

source:
  url: https://github.com/gpuopenanalytics/{{ name }}/archive/{{ version }}.tar.gz
  sha256: b781e49691c7207d5f1e6e95cfc0d14ee9a4a12614da0a43e924de2df047c60f 

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python>=3.5
    - pip
  run:
    - python>=3.5

test:
  imports:
    - pynvml

about:
  home: https://github.com/gpuopenanalytics/{{ name }}
  license: BSD
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Python Bindings for the NVIDIA Management Library'
  description: |
    This is a wrapper around the NVML library. For information about
    the NVML library, see <http://developer.nvidia.com>.
  doc_url: https://pypi.org/project/pynvml/
  dev_url: https://github.com/gpuopenanalytics/pynvml

extra:
  recipe-maintainers:
    - rjzamora
