travis:
  secure:
    BINSTAR_TOKEN: UyMoD5YwMWz2/uBXP3zCk6+7lDTrWNq83TwkGz1NM/IIwmQAGTYHZO2CvKOBnVL6D7AJKkKMt2Jg7mRy5l5WWvV+NhoatEqYEWbvkXXSGnQdGu4eIVklG84/CqFF2gYa4Sh/X+Lvhgc6sdrJlhriRetzGyzH+/3Us6LGwjcj57W6bAeMQaR12oC2ry9qE4724y+/DI1wsTODghySoNy96YtAn/4ibk7io36ylJfZq0wfIBxLuq1QMtyBgStHE64XPNtekGgiFF0AA1qEBAznjkwWzJuaiTAVTH0Ov2kuuh5helGLsUWAQV+6oQPBVc2tzw0PmXKGQ0bY4F85YIWv4EmwC9ksscUaYsSyW2anvjvAOA2FAlQdOQxMM0OjC1OdtG90SGyeUvde+eVDIpfb0gfKRbxnLjJBRdL7jeJa8PIL+YmjyHPLpUAQDFWSLT+Q5B3HbBSYpT5O9ouUJoHqiJRNg6mjgMgBE9bQaxTMLueIfxC9L68z9cxFMOz7QmFq+B9rFnRtfjaHb4CJ1loWPYlFob6drVXuH+GX7CSC6VCtFqpXmbJkpmAcJu78n5ucm9TDoDNhgNJPnmLmgHxc5XGd5De8PRrOYYyHROtfFhXBPv2zYSfXbmgVXeJXnJzDk/na1H5Z9IXpCOOTuDF6Sq37aMa+YZw7FQaS9YGAnEQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
